<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'activate');
$form->prepare();
?>
<div class="site-login">
<h1><?php echo $translate('Create a new password'); ?></h1>
<?php
echo $this->form()->openTag($form);
echo $this->formCollection($form, false);
?>
<button><?php echo $translate('Activate'); ?></button>
<?php echo $this->form()->closeTag(); ?>
</div>
